# Generated by Django 4.0.5 on 2022-07-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_order_foodproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurent_name', models.CharField(max_length=250, unique=True)),
                ('restaurent_address', models.CharField(max_length=250, unique=True)),
                ('restaurent_contact', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='restaurent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.restaurent'),
        ),
    ]
