# Generated by Django 4.0.5 on 2022-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurent_remove_foodproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='restaurent_image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
