# Generated by Django 4.0.5 on 2022-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_restaurent_restaurent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='restaurent_contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
