# Generated by Django 4.0.5 on 2022-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_restaurent_restaurent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='restaurent_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurent',
            name='restaurent_contact',
            field=models.CharField(max_length=10),
        ),
    ]
